name: Atualizar README do Perfil

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite UTC.
                      # Você pode ajustar o cron para uma frequência diferente.
                      # Exemplo: '0 0 * * *' para diariamente, '0 */6 * * *' para a cada 6 horas.
  workflow_dispatch: # Permite que você execute o workflow manualmente na aba 'Actions'.

jobs:
  update-readme-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4 # Use a versão mais recente para melhor compatibilidade

      - name: Configurar Python
        uses: actions/setup-python@v5 # Use a versão mais recente
        with:
          python-version: '3.x' # Versão do Python a ser usada

      - name: Instalar Dependências
        run: pip install PyGithub

      - name: Executar Script de Atualização do README
        run: python .github/scripts/update_readme.py
        env:
          # GITHUB_TOKEN é um token de acesso pessoal que o GitHub Actions fornece automaticamente
          # para o repositório onde o workflow está sendo executado.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commitar e Enviar Alterações
        uses: stefanzweifel/git-auto-commit-action@v5 # Use a versão mais recente
        with:
          commit_message: "Docs: Atualiza dinamicamente as informações do README"
          # Define quais arquivos (ou padrões de arquivos) devem ser commitados
          files: "README.md"
          # Opções para push, 'force-with-lease' é mais seguro que '--force'
          # push_options: "--force-with-lease"
          # Se o workflow falhar por causa de um conflito de push, remova a linha acima.
          # Geralmente não é necessário para atualizações de README.md.
